#!/bin/bash

curl --header "Content-Type: application/json" \
  --header "Accept: application/json" \
  --request POST \
  --data '{"email":"e.gorkavyi@gmail.com","password":"PASS"}' \
  http://localhost:65001/login