#!/bin/bash

curl --header "Content-Type: application/json" \
  --header "Accept: application/json" \
  --request POST \
  --data '{"name":"Сергей Иванов"}' \
  http://212.109.218.84:8888/gamers/create
