name: frontend-deploy

on:
  push:
    branches: ['main']
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: 'frontend'
    strategy:
      matrix:
        node-version: [21.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm i
      - run: npm run build --if-present
